myfileapp/urls.py
from django.urls import path

from . import views


urlpatterns = [    
    path('', views.home, name="home"),
    path('signin', views.signin, name="signin"),
    path('signup', views.signup, name="signup"),
    path('signout', views.signout, name="signout"),
    path('index', views.index, name="index"),
    path('view', views.show_file, name="view")
            
]

myproj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myfileapp.urls'))
  
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myfileapp/models.py
from django.db import models

# Create your models here.

class file_upload(models.Model):
    ids = models.AutoField(primary_key=True)
    file_name = models.CharField(max_length=255)
    my_file = models.FileField(upload_to='')
    
    def __str__(self):
        return self.file_name
    

myfileapp/forms.py
from django import forms


class MyfileUploadForm(forms.Form):
    file_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    files_data = forms.FileField(widget=forms.FileInput(attrs={'class':'form-control'}))

myfileapp/views.py
from multiprocessing import context
import re
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from .forms import MyfileUploadForm
from .models import file_upload


def home(request):
    return render(request, "index1.html")

def signup(request):

    if request.method == "POST":
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']
        if User.objects.filter(username=username): 
            messages.error(request, "Username already exist! Please try some other username.")
            return redirect('home')
        
        if User.objects.filter(email=email).exists():
            messages.error(request, "Email Already Registered!!")
            return redirect('home')
        
        if len(username)>20:
            messages.error(request, "Username must be under 20 charcters!!")
            return redirect('home')
        
        if pass1 != pass2:
            messages.error(request, "Passwords didn't matched!!")
            return redirect('home')
        
        if not username.isalnum():
            messages.error(request, "Username must be Alpha-Numeric!!")
            return redirect('home')
        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname
        myuser.save()
        messages.success(request, "Account created Successfully")
        return redirect("signin")
    return render(request,"signup.html")

def signin(request):
    if request.method=="POST":
        username=request.POST['username']
        pass1=request.POST['pass1'] 
        user = authenticate(username=username, password=pass1)
        if user is not None:
            login(request,user)
            fname=user.first_name
            print('inif block')
            return render(request,"index.html",{'fname': fname})
        else:
            print('else')
            messages.warning(request, "Incorrect Username/Password") 
            return redirect("home")
    else:
        return render(request, "signin.html")

def signout(request):
    logout(request)
    messages.success(request ,"Logged Out Succefully")
    return redirect("home")

def index(request):
    if request.method == 'POST':
        form = MyfileUploadForm(request.POST, request.FILES)
        print(form.as_p)
        if form.is_valid():
            name = form.cleaned_data['file_name']
            the_files = form.cleaned_data['files_data']
            file_upload(file_name=name, my_file=the_files).save()          
            return HttpResponse("file upload")
        else:
            return HttpResponse('error')
    else:
        context = {
            'form':MyfileUploadForm()
        }        
        return render(request, 'index.html', context)
        



def show_file(request):
    # this for testing 
    all_data = file_upload.objects.all()

    context = {
        'data':all_data 
        }

    return render(request, 'view.html', context)
    

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>File Upload</title>
  </head>
  <body>
 
<h1 class="card bg-dark text-white">UPLOAD YOUR FILES HERE</h1>
<div class="container mt-5">
    <form  action="{% url 'index' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
        <div class="form-group">
          <label for="{{form.file_name.id_for_label}}">File Name</label>
          <input type="text" name="file_name" class="form-control" required="" id="id_file_name">
        </div>
        <div class="form-group">
            <label for="{{form.files_data.id_for_label}}">File</label>
            <input type="file" name="files_data" class="form-control" required="" id="id_files_data">
          </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button class="btn btn-primary bg-light" type="submit"><a href="/view">
          view upload</a>
      </form>

</div>
    














    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/index1.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Authentication</title>
    <style>
        body {
            margin: auto;
            background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))
        }

        .mb-5,
        .my-5 {
            margin-bottom: 7rem !important;
        }
    </style>
</head>

<body>
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-dark text-white" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            {% for message in messages %}
                            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                                <strong>Message:</strong> {{ message }}
                                <button type="button" class="close " data-dismiss="alert" area-label="close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                            <h3 class="fw-bold text-uppercase mb-5">WELCOME!</h3>
                            {% if user.is_authenticated %}


                            <h3>Hello {{fname}}!</h3>
                            <h4 class="fw-bold text-uppercase mb-2">You're successfully logged In.</h4>
                            <button class="btn btn-outline-light btn-lg px-5" type="submit"><a href="/signout">
                                    SignOut</a></button>
                            {% else %}
                            <button class="btn btn-outline-light btn-lg px-5" type="submit"><a href="/signin">
                                    SignIn</a></button>
                            <button class="btn btn-outline-light btn-lg px-5" type="submit"><a href="/signup">
                                    SignUp</a></button>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

templates/signin.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Sign In</title>
    <style>
        body {
            background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))
        }
    </style>
</head>

<body>
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-dark text-white" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            <h2 class="fw-bold mb-2 text-uppercase">SIGN IN</h2>
                            <p class="text-white-50 mb-5">Please enter your Username and password!</p>
                            <form action="{% url 'signin' %}" method="post">
                                {% csrf_token %}
                                <div class="form-outline form-white mb-4">
                                    <label class="form-label" for="">Username</label>
                                    <input type="text" class="form-control form-control-lg" id="username" name="username"
                                        placeholder="Enter Username">
                                </div>
                                <div class="form-outline form-white mb-4">
                                    <label class="form-label" for="">Password</label>
                                    <input type="password" class="form-control form-control-lg" id="pass1" name="pass1"
                                        placeholder="Enter Password">
                                </div>
                                <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>            <!-- <h1>Hello, world!</h1>  -->

            <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
                integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
                crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
                integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
                crossorigin="anonymous"></script>
</body>

</html>

templates/signup.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <title>SignUp</title>
  <style>
    body {
      margin: auto;
      background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))
    }
  </style>
</head>

<body>
  <section class="vh-100 gradient-custom">
    <div class="container py-4 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-4 text-center">
              <h3 class="fw-bold mb-2 text-uppercase">Sign Up</h3>
              <p class="text-white-50 ">Fill the information given below.</p>
              <form action="/signup" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label class="form-label" for="">Username</label>
                  <input type="text" class="form-control form-control-lg" id="username" name="username"
                    placeholder="Create a username" required>
                  <br>
                  <label class="form-label" for="">First Name</label>
                  <input type="text" class="form-control form-control-lg" id="fname" name="fname"
                    placeholder="Enter Your First Name" required>
                  <br>
                  <label class="form-label" for="">Last Name</label>
                  <input type="text" class="form-control form-control-lg" id="lname" name="lname"
                    placeholder="Enter Your Last Name" required>
                  <br>
                  <label class="form-label" for="">Email Address</label>
                  <input type="text" class="form-control form-control-lg" id="email" name="email"
                    placeholder="Enter Your Email Address" required>
                  <br>
                  <label class="form-label" for="">Password</label>
                  <input type="password" class="form-control form-control-lg" id="pass1" name="pass1"
                    placeholder="Create Your Password" required>
                  <br>
                  <label class="form-label" for="">Confirm Password</label>
                  <input type="password" class="form-control form-control-lg" id="pass2" name="pass2"
                    placeholder="Confirm Your Password" required>
                  <br>
                  <button type="submit" class="btn btn-light">Submit</button>
                </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  </form>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
</body>

</html>

templates/view.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
      <style>
        
      </style>
</head>

<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-12">

                <table class="table">
                    <thead>
                      <tr>
                        <th >S/N</th>
                        <th >Name</th>
                        <th >File Link</th>
                        <th >download</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for d in data %}
                      <tr>
                        <th>{{forloop.counter}}</th>
                        <th>{{d.file_name}}</th>
                        <th><a  href="{{d.my_file.url}}">{{d.my_file}}</a></th>
                        <th><a download href="{{d.my_file.url}}">{{d.my_file}}</a></th>
                        
                       
                      </tr>
                      {% endfor %}
                     
                    </tbody>
                  </table>



            </div>
        </div>
        <button class="btn btn-primary bg-light" type="submit"><a href="/signout">
          SignOut</a></button>
        <button class="btn btn-primary bg-light" type="submit"><a href="/index">
            Back</a>
    </div>
    
    

</body>

</html>